### ISSUE TITLE
OutOfMemoryError when unpacking large 7z archives

### ISSUE THREAD

**Issue by GijsvandenHoven** [WirelessAlien/ZipXtract#2]
I received the following crash log after trying to unpack a 900 MB 7z file:

```
type: crash
osVersion: google/bluejay/bluejay:13/TQ3A.230805.001/2023080800:user/release-keys
package: com.wirelessalien.zipxtract:2
process: com.wirelessalien.zipxtract
processUptime: 4716 + 198 ms
installer: com.android.packageinstaller

java.lang.OutOfMemoryError: Failed to allocate a 903776800 byte allocation with 25165824 free bytes and 254MB until OOM, target footprint 26639440, growth limit 268435456
    at java.io.ByteArrayOutputStream.<init>(ByteArrayOutputStream.java:79)
    at kotlin.io.ByteStreamsKt.readBytes(IOStreams.kt:135)
    at com.wirelessalien.zipxtract.MainActivity.extract7z(MainActivity.kt:310)
    at com.wirelessalien.zipxtract.MainActivity.extractArchiveFile(MainActivity.kt:187)
    at com.wirelessalien.zipxtract.MainActivity.onCreate$lambda$4(MainActivity.kt:89)
    at com.wirelessalien.zipxtract.MainActivity.$r8$lambda$XY9q3LKhqmtgD8C_7Tk-br1zLk4(Unknown Source:0)
    at com.wirelessalien.zipxtract.MainActivity$$ExternalSyntheticLambda5.onClick(Unknown Source:2)
    at android.view.View.performClick(View.java:7542)
    at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1211)
    at android.view.View.performClickInternal(View.java:7519)
    at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
    at android.view.View$PerformClick.run(View.java:29476)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7940)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ExecInit.main(ExecInit.java:49)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
```

I rebooted the phone to free up any memory that may be used by other applications and tried again, to the same outcome. Upon closer inspection of the error message, it looks like the app may never be allowed by the OS to grow beyond ~250MB memory.

The device is a Google Pixel 6a, running GrapheneOS.

Taking a quick look at the source code around the stack trace, I guess it is because `bufferedInputStream.readBytes()` tries to turn the entire file into a byte array, which inevitably runs into trouble if you throw large enough files at it.

You are possibly already aware of this, since it seems `extract7z` is the only unpacking function that does this. Meanwhile all the others stick to streams.

I know almost nothing about Kotlin and this file format so I am unable to offer any advice on it. This could just be an annoying limitation of 7Z files in general, or be specific to the SevenZFile class.

Feel free to let me know if you need any more information. I suspect there is no easy fix for this problem, and maybe it's not even worth fixing at all (?)

**Comment by WirelessAlien** [comment]
> You are possibly already aware of this, since it seems `extract7z` is the only unpacking function that does this. Meanwhile all the others stick to streams.
> 

Maybe I did but now I don't remember why 7z code was formatted like that😐,  maybe that was library limitation. 

> I know almost nothing about Kotlin and this file format so I am unable to offer any advice on it. This could just be an annoying limitation of 7Z files in general, or be specific to the SevenZFile class.
> 

I am also not a pro in kotlin, I am just trying to learn 😄 . 

> Feel free to let me know if you need any more information. I suspect there is no easy fix for this problem, and maybe it's not even worth fixing at all (?)

Thanks.
I think it will not be so hard to fix. I will fix it ( _I will try to fix it_👍)

**Comment by WirelessAlien** [comment]
> 
> > You are possibly already aware of this, since it seems `extract7z` is the only unpacking function that does this. Meanwhile all the others stick to streams.
> > 
> 
> Maybe I did but now I don't remember why 7z code was formatted like that😐,  maybe that was library limitation. 
> 
> > I know almost nothing about Kotlin and this file format so I am unable to offer any advice on it. This could just be an annoying limitation of 7Z files in general, or be specific to the SevenZFile class.
> > 
> 
> I am also not a pro in kotlin, I am just trying to learn 😄 . 
> 
> > Feel free to let me know if you need any more information. I suspect there is no easy fix for this problem, and maybe it's not even worth fixing at all (?)
> 
> Thanks.
> I think it will not be so hard to fix. I will fix it ( __I will try to fix it_👍)
> 
>

**Comment by WirelessAlien** [comment]
Fixed
